# Generated by Django 5.1.6 on 2025-02-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='url',
        ),
    ]
