# Generated by Django 5.1.6 on 2025-02-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_education_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la tecnología')),
                ('image', models.ImageField(blank=True, null=True, upload_to='techs', verbose_name='Imagen de la tecnología')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='home.technology', verbose_name='Tecnologías'),
        ),
    ]
