# Generated by Django 5.1.6 on 2025-02-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_technology_education_technologies'),
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.AlterField(
            model_name='education',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='technologies.technologies', verbose_name='Tecnologías'),
        ),
    ]
