# Generated by Django 5.1.6 on 2025-02-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('image', models.ImageField(upload_to='img', verbose_name='imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion')),
            ],
            options={
                'verbose_name': 'tecnologia',
                'verbose_name_plural': 'tecnologias',
                'ordering': ['-created'],
            },
        ),
    ]
